AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - "**/Rakefile"
    - "**/config.ru"
  Exclude:
    - "bin/**/*"
    - "db/**/*"

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/FileName:
  Exclude:
    - "Gemfile"

Style/SymbolArray:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/EmptyMethod:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 20

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
