default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: fcci_development

test:
  <<: *default
  database: fcci_test

production:
  url:  <%= ENV.fetch("DATABASE_URL") if Rails.env.production? %>
